project:
  type: website
  output-dir: docs

website:
  title: "Steven Le"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd
      - f1-racetracks.qmd
    background: "#dfc7b4"

format:
  html:
    theme: 
    - sandstone
    - styles.scss
    mainfont: Gelasio 
    toc: true
    page-layout: full



